In [14]:
import numpy as np
a = np.array([1, 2, 3])           #set up a numpy array
print(a)

print(a[0], " ", a[1], " ", a[2])

print(type(a))
print(a.shape)

[1 2 3]
1   2   3
<class 'numpy.ndarray'>
(3,)


In [15]:
b = np.arange(12)
b    #shows whats in b or print(b):prints whats stored in b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
print(b.shape)
b.reshape(3,4)

(12,)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
c = np.array([[1,9,2],[7, 16, 5] ,[4,8,3]])
print(c)
print("R,C:", c.shape)
print("DIMENTION:",c.ndim)
print("ITEM SIZE:", c.itemsize)

[[ 1  9  2]
 [ 7 16  5]
 [ 4  8  3]]
R,C: (3, 3)
DIMENTION: 2
ITEM SIZE: 4


In [123]:
# Creating a random N array
n = np.random.randn(5)
n

array([-0.36400945, -0.47277949,  0.72527413,  0.27031457, -0.73554103])

In [73]:
c = np.array([[1,9,2],[7, 16, 5] ,[4,8,3]], dtype = np.float64)      #converting integer array to float using Data types
c

array([[ 1.,  9.,  2.],
       [ 7., 16.,  5.],
       [ 4.,  8.,  3.]])

In [67]:
c = np.array([[1,9,2],[7, 16, 5] ,[4,8,3]], dtype = np.complex)      #converting array to complex
c

array([[ 1.+0.j,  9.+0.j,  2.+0.j],
       [ 7.+0.j, 16.+0.j,  5.+0.j],
       [ 4.+0.j,  8.+0.j,  3.+0.j]])

In [75]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
#python array occupies more memeory
import sys
import time
x = range(1000)

print(sys.getsizeof(5)* len(x)) 

28000


In [52]:
#numby occupies less memeory
x = np.arange(1000)             
print(x.itemsize*x.size)   

4000


In [53]:
#python list takes longer time than numpy array
size = 10000
L1 = range(size)
L2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)

In [69]:
start = time.time()                                   #starts the time 
result = [(x,y) for x,y in zip(L1, L2)]
print("Python list took:", (time.time() - start)*1000)

Python list took: 4.899501800537109


In [74]:
start =time.time()
result = A1+A2
print("Numpy array took:", (time.time() - start)*1000)

Numpy array took: 0.0


In [78]:
# concatenation
print("CONCAT 2 CHAR:\n", np.char.add(['hello','world'], ['abc','xyz']))

CONCAT 2 CHAR:
 ['helloabc' 'worldxyz']


In [83]:
print(np.char.multiply('HELLO ', 4))

HELLO HELLO HELLO HELLO 


In [88]:
print(np.char.center('HELLO', 40, fillchar = '-'))

-----------------HELLO------------------


In [93]:
print(np.char.capitalize('heLLo WORLD'))          #capitalizes only the 1st alpabet of the 1st word

Hello world


In [94]:
print(np.char.title('it capitalizes first alpabhet of each word!'))

It Capitalizes First Alpabhet Of Each Word!


In [100]:
print(np.char.lower(['HELLO' , 'WORLD']))
print(np.char.lower('HELLO WORLD'))

['hello' 'world']
hello world


In [104]:
print(np.char.upper(['hello' , 'World']))
print(np.char.upper('hello World'))

['HELLO' 'WORLD']
HELLO WORLD


In [106]:
print(np.char.split('it splits each of words in a statement!'))

['it', 'splits', 'each', 'of', 'words', 'in', 'a', 'statement!']


In [110]:
print(np.char.splitlines('Hello World\nnow it splits again!'))

['Hello World', 'now it splits again!']


In [120]:
print(np.char.strip(["alpha", "etta" , "alkon"],"a"))

['lph' 'ett' 'lkon']


In [121]:
print(np.char.join([':','-'], ['month','year']))

['m:o:n:t:h' 'y-e-a-r']


In [122]:
print(np.char.replace('It is true.', 'is', 'was'))

It was true.
